# Generated by Django 6.1 on 2026-08-10 14:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_osm', models.CharField(blank=True, choices=[('NODE', 'Node'), ('WAY', 'Way'), ('RELATION', 'Relation')], max_length=10, null=True)),
                ('identifiant_osm', models.BigIntegerField(blank=True, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('nom_normalise', models.CharField(db_index=True, max_length=255)),
                ('categorie', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=500)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(max_length=255)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('source', models.CharField(choices=[('OPENSTREETMAP', 'OpenStreetMap'), ('UTILISATEUR', 'Soumission utilisateur')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuve'), ('REJETE', 'Rejete'), ('FUSIONNE', 'Fusionne')], default='EN_ATTENTE', max_length=20)),
                ('score_popularite', models.IntegerField(default=0)),
                ('fusionne_dans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lieux_fusionnes', to='places.lieu')),
            ],
            options={
                'db_table': 'lieu',
            },
        ),
        migrations.CreateModel(
            name='AdresseEnregistree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(choices=[('DOMICILE', 'Domicile'), ('TRAVAIL', 'Travail'), ('PERSONNALISE', 'Personnalise')], max_length=20)),
                ('nom_personnalise', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.CharField(max_length=500)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adresses_enregistrees', to='places.lieu')),
            ],
            options={
                'db_table': 'adresse_enregistree',
            },
        ),
        migrations.CreateModel(
            name='RechercheRecente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=255)),
                ('sous_libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('recherche_le', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_recentes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recherche_recente',
                'ordering': ['-recherche_le'],
            },
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(fields=['ville', 'categorie'], name='lieu_ville_6e4082_idx'),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=models.Index(fields=['position'], name='lieu_positio_72cb02_idx'),
        ),
        migrations.AddConstraint(
            model_name='lieu',
            constraint=models.UniqueConstraint(condition=models.Q(('identifiant_osm__isnull', False)), fields=('type_osm', 'identifiant_osm'), name='uniq_lieu_osm'),
        ),
        migrations.AddConstraint(
            model_name='adresseenregistree',
            constraint=models.UniqueConstraint(condition=models.Q(('libelle__in', ['DOMICILE', 'TRAVAIL'])), fields=('utilisateur', 'libelle'), name='uniq_domicile_travail_par_utilisateur'),
        ),
        migrations.AddIndex(
            model_name='rechercherecente',
            index=models.Index(fields=['utilisateur', '-recherche_le'], name='recherche_r_utilisa_0ea466_idx'),
        ),
    ]
