# Generated by Django 6.1 on 2026-08-21 16:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='lieu',
            name='propose_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lieux_proposes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lieu',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_normalise'], name='lieu_nom_normalise_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
