# Generated by Django 6.1 on 2026-08-27 09:43

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_lieu_propose_par_lieu_lieu_nom_normalise_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('nom_normalise', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('population', models.IntegerField(default=0)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'ville',
                'indexes': [models.Index(fields=['nom_normalise'], name='ville_nom_nor_83e032_idx'), models.Index(fields=['position'], name='ville_positio_3993ea_idx')],
            },
        ),
    ]
