# Generated by Django 6.1 on 2026-08-27 10:39

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_ville'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ville',
            name='ville_nom_nor_83e032_idx',
        ),
        migrations.AddIndex(
            model_name='ville',
            index=django.contrib.postgres.indexes.GinIndex(fields=['nom_normalise'], name='ville_nom_normalise_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
