# Generated by Django 6.1 on 2026-09-11 11:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_ville_ville_nom_nor_83e032_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('HOPITAL', 'Hopital'), ('GARAGE', 'Garage')], max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=500)),
                ('ville', models.CharField(blank=True, max_length=255)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('visible_sur_carte', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etablissements_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'etablissement',
                'indexes': [models.Index(fields=['position'], name='etablisseme_positio_d71d63_idx')],
            },
        ),
    ]
