# Generated by Django 6.1 on 2026-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_etablissement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lieu',
            name='motif_rejet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
