# Generated by Django 6.1 on 2026-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_lieu_cree_le_lieu_motif_rejet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='source',
            field=models.CharField(choices=[('OPENSTREETMAP', 'OpenStreetMap'), ('UTILISATEUR', 'Soumission utilisateur'), ('BACK_OFFICE', 'Ajout back-office')], max_length=20),
        ),
    ]
