# Generated by Django 6.1 on 2026-08-10 14:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DANGER', 'Danger'), ('POLICE', 'Police'), ('EMBOUTEILLAGE', 'Embouteillage'), ('ACCIDENT', 'Accident'), ('ROUTE_BARREE', 'Route barree'), ('VOIE_BLOQUEE', 'Voie bloquee'), ('MAUVAIS_TEMPS', 'Mauvais temps'), ('RADAR', 'Radar')], max_length=20)),
                ('sous_type', models.CharField(blank=True, max_length=100, null=True)),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('cellule_h3_res8', models.BigIntegerField()),
                ('cellule_h3_res7', models.BigIntegerField()),
                ('cap', models.IntegerField(blank=True, help_text='degres, 0-359', null=True)),
                ('nom_voie', models.CharField(blank=True, max_length=255)),
                ('confirmations', models.IntegerField(default=0)),
                ('infirmations', models.IntegerField(default=0)),
                ('score_confiance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACTIF', 'Actif'), ('EXPIRE', 'Expire'), ('RETIRE', 'Retire'), ('FUSIONNE', 'Fusionne')], default='ACTIF', max_length=20)),
                ('severite', models.IntegerField(default=1)),
                ('expire_le', models.DateTimeField()),
                ('motif_retrait', models.CharField(blank=True, max_length=255, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_signales', to=settings.AUTH_USER_MODEL)),
                ('fusionne_dans', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_fusionnes', to='community.incident')),
            ],
            options={
                'db_table': 'incident',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sens', models.CharField(choices=[('CONFIRMATION', 'Confirmation'), ('INFIRMATION', 'Infirmation')], max_length=20)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='community.incident')),
                ('votant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vote',
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['cellule_h3_res8', 'statut'], name='incident_cellule_6c2998_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['statut', 'expire_le'], name='incident_statut_6005eb_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['position'], name='incident_positio_f49000_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('incident', 'votant'), name='uniq_vote_par_utilisateur_et_incident'),
        ),
    ]
