# Generated by Django 6.1 on 2026-08-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='cellule_h3_res7',
            field=models.BigIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='incident',
            name='cellule_h3_res8',
            field=models.BigIntegerField(editable=False),
        ),
    ]
