# Generated by Django 6.1 on 2026-08-25 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_incident_cellule_h3_res7_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ville',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='ville_normalisee',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['ville_normalisee', 'statut'], name='incident_ville_n_4bf135_idx'),
        ),
    ]
