# Generated by Django 6.1 on 2026-09-02 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_incident_ville_incident_ville_normalisee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='forward_osm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='way_id_osm',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['way_id_osm', 'forward_osm'], name='incident_way_id__b88cbc_idx'),
        ),
    ]
