# Generated by Django 6.1 on 2026-10-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_incident_forward_osm_incident_way_id_osm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='en_agglomeration',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
