# Generated by Django 6.1 on 2026-08-10 14:37

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('identifiant_google', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('nom_complet', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=32, null=True)),
                ('ville', models.CharField(blank=True, max_length=255, null=True)),
                ('type_vehicule', models.CharField(blank=True, choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('TAXI', 'Taxi'), ('CAMION', 'Camion'), ('BUS', 'Bus'), ('UTILITAIRE', 'Utilitaire')], max_length=20, null=True)),
                ('url_avatar', models.URLField(blank=True, null=True)),
                ('email_verifie', models.BooleanField(default=False)),
                ('mode_invisible', models.BooleanField(default=False)),
                ('formule', models.CharField(choices=[('GRATUITE', 'Gratuite'), ('PREMIUM', 'Premium')], default='GRATUITE', max_length=20)),
                ('formule_expire_le', models.DateTimeField(blank=True, null=True)),
                ('score_reputation', models.IntegerField(default=100)),
                ('points', models.IntegerField(default=0)),
                ('est_banni', models.BooleanField(default=False)),
                ('banni_jusqu_a', models.DateTimeField(blank=True, null=True)),
                ('cgu_acceptee_le', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'utilisateur',
            },
            managers=[
                ('objects', accounts.models.UtilisateurManager()),
            ],
        ),
        migrations.CreateModel(
            name='Droits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formule', models.CharField(choices=[('GRATUITE', 'Gratuite'), ('PREMIUM', 'Premium')], default='GRATUITE', max_length=20)),
                ('max_adresses_enregistrees', models.IntegerField(default=5)),
                ('publicite_active', models.BooleanField(default=True)),
                ('routage_avance', models.BooleanField(default=False)),
                ('packs_hors_ligne', models.BooleanField(default=False)),
                ('retention_historique_jours', models.IntegerField(default=30)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='droits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'droits',
                'db_table': 'droits',
            },
        ),
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eviter_peages', models.BooleanField(default=False)),
                ('eviter_non_bitumees', models.BooleanField(default=False)),
                ('eviter_intersections_difficiles', models.BooleanField(default=False)),
                ('style_carte', models.CharField(default='STANDARD', max_length=50)),
                ('guidage_vocal_actif', models.BooleanField(default=True)),
                ('langue_vocale', models.CharField(default='fr', max_length=10)),
                ('unites', models.CharField(choices=[('KM', 'Kilometres'), ('MI', 'Miles')], default='KM', max_length=5)),
                ('compteur_vitesse_actif', models.BooleanField(default=False)),
                ('alerte_vitesse_active', models.BooleanField(default=True)),
                ('notifications_globales', models.BooleanField(default=True)),
                ('notif_annonces', models.BooleanField(default=True)),
                ('notif_incidents_frequents', models.BooleanField(default=True)),
                ('notif_alertes_police', models.BooleanField(default=True)),
                ('notif_changement_itineraire', models.BooleanField(default=True)),
                ('notif_nouveautes', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parametres',
            },
        ),
        migrations.CreateModel(
            name='Appareil',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jeton_push', models.CharField(max_length=255)),
                ('plateforme', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10)),
                ('version_application', models.CharField(max_length=20)),
                ('version_systeme', models.CharField(max_length=20)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('vu_le', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appareils', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appareil',
                'indexes': [models.Index(fields=['jeton_push'], name='appareil_jeton_p_839abb_idx'), models.Index(fields=['utilisateur', 'est_actif'], name='appareil_utilisa_14b9a4_idx')],
            },
        ),
    ]
