# Generated by Django 6.1 on 2026-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='droits',
            name='id',
        ),
        migrations.RemoveField(
            model_name='droits',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='suppression_demandee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='droits',
            name='formule',
            field=models.CharField(choices=[('GRATUITE', 'Gratuite'), ('PREMIUM', 'Premium')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='droits',
            name='max_adresses_enregistrees',
            field=models.IntegerField(blank=True, help_text='null = illimite', null=True),
        ),
    ]
