# Generated by Django 6.1 on 2026-09-01 13:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_seed_droits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='score_reputation',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=6),
        ),
    ]
