# Generated by Django 6.1 on 2026-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_score_reputation_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
