# Generated by Django 6.1 on 2026-09-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_utilisateur_email_alter_utilisateur_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='afficher_limite_vitesse',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametres',
            name='tolerance_vitesse_kmh',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
