# Generated by Django 6.1 on 2026-10-03 07:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_parametres_compteur_vitesse'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionListeAttente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('profil', models.CharField(choices=[('AUTOMOBILISTE', 'Automobiliste'), ('CHAUFFEUR_PRO', 'Chauffeur professionnel (taxi, moto-taxi, VTC)'), ('FLOTTE', 'Gestionnaire de flotte / entreprise'), ('AGENCE_VOYAGE', 'Agence de voyage')], default='AUTOMOBILISTE', max_length=20)),
                ('type_vehicule', models.CharField(blank=True, choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('TAXI', 'Taxi'), ('CAMION', 'Camion'), ('BUS', 'Bus'), ('UTILITAIRE', 'Utilitaire')], max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('contacte', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inscription_liste_attente',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['profil', 'contacte'], name='inscription_profil_50bdf7_idx')],
            },
        ),
    ]
