# Generated by Django 6.1 on 2026-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_liste_attente'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='mises_a_jour_auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parametres',
            name='rayon_chargement_km',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
