# Generated by Django 6.1 on 2026-10-03 07:55

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def convertir_ancien_bareme(apps, schema_editor):
    # Ancien bareme : 5 points par signalement valide, seule source de points.
    # Nouveau : 1 point -- diviser par 5 conserve le nombre de signalements
    # valides deja acquis.
    Utilisateur = apps.get_model('accounts', 'Utilisateur')
    Utilisateur.objects.filter(points__gt=0).update(points=F('points') / 5)


def revenir_ancien_bareme(apps, schema_editor):
    Utilisateur = apps.get_model('accounts', 'Utilisateur')
    Utilisateur.objects.filter(points__gt=0).update(points=F('points') * 5)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_parametres_maj_auto_rayon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.RunPython(convertir_ancien_bareme, revenir_ancien_bareme),
    ]
