# Generated by Django 6.1 on 2026-08-10 14:37

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagnePublicitaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('annonceur', models.CharField(max_length=255)),
                ('url_creation', models.URLField()),
                ('url_cible', models.URLField()),
                ('emplacement', models.CharField(choices=[('BANNIERE_RECHERCHE', 'Banniere de recherche'), ('RESUME_ITINERAIRE', "Resume d'itineraire"), ('CARTE_ARRIVEE', "Carte d'arrivee"), ('EPINGLE_CARTE', 'Epingle carte')], max_length=20)),
                ('villes_ciblees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('zone_ciblee', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('debute_le', models.DateTimeField()),
                ('termine_le', models.DateTimeField()),
                ('plafond_journalier', models.IntegerField()),
                ('est_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'campagne_publicitaire',
                'indexes': [models.Index(fields=['est_active', 'debute_le', 'termine_le'], name='campagne_pu_est_act_9c0096_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntreeAudit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('type_cible', models.CharField(max_length=100)),
                ('identifiant_cible', models.UUIDField()),
                ('valeur_precedente', models.JSONField(blank=True, null=True)),
                ('valeur_nouvelle', models.JSONField(blank=True, null=True)),
                ('survenue_le', models.DateTimeField(auto_now_add=True)),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrees_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'entree_audit',
                'indexes': [models.Index(fields=['type_cible', 'identifiant_cible'], name='entree_audi_type_ci_82d903_idx'), models.Index(fields=['-survenue_le'], name='entree_audi_survenu_34f271_idx')],
            },
        ),
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('evenement', models.CharField(help_text='TypeEvenement : valeurs non enumerees dans le document source', max_length=50)),
                ('survenue_le', models.DateTimeField(auto_now_add=True)),
                ('campagne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='ads_admin.campagnepublicitaire')),
            ],
            options={
                'db_table': 'impression',
                'indexes': [models.Index(fields=['campagne', 'survenue_le'], name='impression_campagn_d350e3_idx')],
            },
        ),
    ]
