# Generated by Django 6.1 on 2026-10-08 08:43

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_points_decimaux'),
        ('ads_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferencesNotificationStaff',
            fields=[
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences_notifications_staff', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('types_desactives', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list)),
                ('navigateur', models.BooleanField(default=False)),
                ('son', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'preferences_notification_staff',
            },
        ),
        migrations.CreateModel(
            name='NotificationStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('LIEU', 'Lieu propose'), ('INCIDENT', 'Incident conteste'), ('ABUS', 'Comportement suspect'), ('ATTENTE', "Liste d'attente"), ('IMPORT', 'Import'), ('PUB', 'Publicite')], max_length=20)),
                ('niveau', models.CharField(choices=[('INFO', 'Info'), ('SUCCES', 'Succes'), ('ATTENTION', 'Attention'), ('DANGER', 'Danger')], default='INFO', max_length=20)),
                ('titre', models.CharField(max_length=255)),
                ('texte', models.CharField(blank=True, max_length=500)),
                ('lien', models.CharField(blank=True, max_length=255)),
                ('cle_regroupement', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('compteur', models.PositiveIntegerField(default=1)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('lue_par', models.ManyToManyField(blank=True, related_name='notifications_staff_lues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_staff',
                'indexes': [models.Index(fields=['-mis_a_jour_le'], name='notificatio_mis_a_j_d2ffeb_idx')],
            },
        ),
    ]
