# Generated by Django 6.1 on 2026-10-03 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('libelle_normalise', models.CharField(editable=False, max_length=255, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('amende_fcfa', models.PositiveIntegerField()),
                ('amende_max_fcfa', models.PositiveIntegerField(blank=True, null=True)),
                ('reference_legale', models.CharField(blank=True, max_length=255)),
                ('sanctions_complementaires', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'infraction',
                'ordering': ['categorie', 'libelle'],
                'indexes': [models.Index(fields=['actif', 'categorie'], name='infraction_actif_1fb383_idx')],
            },
        ),
    ]
