# Generated by Django 6.1 on 2026-08-10 14:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EchantillonVitesse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identifiant_arete', models.BigIntegerField(help_text='identifiant de segment sur le graphe routier')),
                ('debut_intervalle', models.DateTimeField()),
                ('jour_semaine', models.PositiveSmallIntegerField()),
                ('heure_jour', models.PositiveSmallIntegerField()),
                ('vitesse_moyenne', models.DecimalField(decimal_places=2, help_text='km/h', max_digits=6)),
                ('nombre_echantillons', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'echantillon_vitesse',
                'indexes': [models.Index(fields=['identifiant_arete', '-debut_intervalle'], name='echantillon_identif_deebd2_idx')],
                'constraints': [models.UniqueConstraint(fields=('identifiant_arete', 'debut_intervalle'), name='uniq_echantillon_par_arete_intervalle')],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_origine', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('libelle_origine', models.CharField(max_length=500)),
                ('position_destination', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('libelle_destination', models.CharField(max_length=500)),
                ('itineraire_choisi', models.CharField(help_text="identifiant de l'Itineraire retenu", max_length=64)),
                ('distance_prevue', models.IntegerField(help_text='metres')),
                ('duree_prevue', models.IntegerField(help_text='secondes')),
                ('distance_reelle', models.IntegerField(blank=True, help_text='metres', null=True)),
                ('duree_reelle', models.IntegerField(blank=True, help_text='secondes', null=True)),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifie'), ('ACTIF', 'Actif'), ('TERMINE', 'Termine'), ('ANNULE', 'Annule')], default='PLANIFIE', max_length=20)),
                ('incidents_evites', models.IntegerField(default=0)),
                ('note', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('demarre_le', models.DateTimeField(blank=True, null=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
                ('lieu_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajets', to='places.lieu')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trajet',
            },
        ),
        migrations.CreateModel(
            name='Itineraire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifiant', models.CharField(help_text='cle correlee a Trajet.itineraire_choisi', max_length=64)),
                ('est_recommande', models.BooleanField(default=False)),
                ('libelle', models.CharField(max_length=255)),
                ('distance', models.IntegerField(help_text='metres')),
                ('duree', models.IntegerField(help_text='secondes')),
                ('duree_avec_trafic', models.IntegerField(blank=True, help_text='secondes', null=True)),
                ('niveau_trafic', models.CharField(choices=[('NORMAL', 'Normal'), ('MODERE', 'Modere'), ('DENSE', 'Dense')], default='NORMAL', max_length=10)),
                ('geometrie', models.TextField(help_text='polyligne encodee, telle que retournee par Valhalla')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraires', to='trips.trajet')),
            ],
            options={
                'db_table': 'itineraire',
            },
        ),
        migrations.CreateModel(
            name='Manoeuvre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveIntegerField(help_text='position dans la sequence de guidage (non documente, ajoute par necessite)')),
                ('type', models.CharField(help_text='TypeManoeuvre : valeurs non enumerees dans le document source', max_length=50)),
                ('instruction', models.CharField(max_length=500)),
                ('instruction_vocale', models.CharField(max_length=500)),
                ('distance', models.IntegerField(help_text='metres')),
                ('duree', models.IntegerField(help_text='secondes')),
                ('nom_voie', models.CharField(blank=True, max_length=255)),
                ('itineraire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manoeuvres', to='trips.itineraire')),
            ],
            options={
                'db_table': 'manoeuvre',
                'ordering': ['itineraire', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('itineraire', 'ordre'), name='uniq_manoeuvre_ordre_par_itineraire')],
            },
        ),
        migrations.AddIndex(
            model_name='trajet',
            index=models.Index(fields=['utilisateur', 'statut'], name='trajet_utilisa_45c576_idx'),
        ),
        migrations.AddConstraint(
            model_name='trajet',
            constraint=models.CheckConstraint(condition=models.Q(('note__isnull', True), models.Q(('note__gte', 1), ('note__lte', 5)), _connector='OR'), name='note_trajet_entre_1_et_5'),
        ),
        migrations.AddConstraint(
            model_name='itineraire',
            constraint=models.UniqueConstraint(fields=('trajet', 'identifiant'), name='uniq_itineraire_par_trajet'),
        ),
    ]
