# Generated by Django 6.1 on 2026-08-28 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manoeuvre',
            name='road_class',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
