# Generated by Django 6.1 on 2026-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_manoeuvre_road_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manoeuvre',
            name='road_class',
            field=models.CharField(choices=[('URBAIN', 'Urbain'), ('NATIONALE', 'Nationale'), ('AUTOROUTE', 'Autoroute')], default='URBAIN', max_length=20),
        ),
    ]
