# Generated by Django 6.1 on 2026-09-11 11:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_manoeuvre_road_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneVitesse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('point_depart', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('point_arrivee', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(blank=True, geography=True, null=True, srid=4326)),
                ('vitesse_max_kmh', models.PositiveSmallIntegerField()),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_vitesse_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zone_vitesse',
            },
        ),
    ]
