# Generated by Django 6.1 on 2026-09-12 01:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_zonevitesse'),
    ]

    operations = [
        migrations.AddField(
            model_name='manoeuvre',
            name='arrivee_etape_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EtapeTrajet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre', models.PositiveIntegerField(help_text='position dans la sequence origine -> etapes -> destination')),
                ('position', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='trips.trajet')),
            ],
            options={
                'db_table': 'etape_trajet',
                'ordering': ['trajet', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('trajet', 'ordre'), name='uniq_etape_ordre_par_trajet')],
            },
        ),
    ]
