# Generated by Django 6.1 on 2026-09-19 00:54

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_manoeuvre_arrivee_etape_index_etapetrajet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridorReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('ville_depart', models.CharField(max_length=255)),
                ('ville_arrivee', models.CharField(max_length=255)),
                ('ancrage_depart', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('ancrage_arrivee', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('rayon_ancrage_m', models.PositiveIntegerField(default=25000)),
                ('geometrie', django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326)),
                ('fractions_sommets', models.JSONField()),
                ('distance_m', models.PositiveIntegerField()),
                ('duree_s', models.PositiveIntegerField()),
                ('libelles_voies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('manoeuvres_reference', models.JSONField(blank=True, default=list)),
                ('actif', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corridors_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corridor_reference',
                'indexes': [models.Index(fields=['geometrie'], name='corridor_re_geometr_020d97_idx')],
            },
        ),
    ]
