# Generated by Django 6.1 on 2026-10-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_corridorreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_derniere_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_distance_m',
            field=models.PositiveIntegerField(default=0, help_text="somme des ecarts entre positions consecutives d'un meme lot"),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_lots',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_nb_vitesses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_positions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_premiere_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_somme_vitesses',
            field=models.FloatField(default=0, help_text='km/h, pour la moyenne'),
        ),
        migrations.AddField(
            model_name='trajet',
            name='telemetrie_vitesse_max',
            field=models.FloatField(blank=True, help_text='km/h', null=True),
        ),
    ]
